### ISSUE TITLE
Infinity loop

### ISSUE THREAD

**Issue by alphaonex86** [fangdingjun/dnsproxy#2]
#0  calloc (num=800, size=1) at /mnt/data/perso/travail/confiared/dnsproxy-master/third-part/ldns-1.6.17/compat/calloc.c:17
#1  0x0000555555571872 in split (str=0x55555584f290 "8.8.8.8,8.8.4.4", comma=44) at /mnt/data/perso/travail/confiared/dnsproxy-master/src/parse_cfg.c:113
#2  0x0000555555571c60 in parse_cfg (filename=<optimized out>, args=0x555555846020 <arguments>) at /mnt/data/perso/travail/confiared/dnsproxy-master/src/parse_cfg.c:213
#3  0x000055555556e9d6 in main (argc=3, argv=0x7fffffffd8e8) at /mnt/data/perso/travail/confiared/dnsproxy-master/src/dnsproxy.c:796

**Comment by fangdingjun** [comment]
It looks like that the bug in the configure file parse part, could you
provide the config cause this bug?

2018年1月10日 01:20，"BRULE Herman" <notifications@github.com>写道：
